/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "clients.create": [],
    "clients.store": [],
    "clients.edit": [
        {
            "name": "client",
            "required": true
        }
    ],
    "clients.update": [
        {
            "name": "client",
            "required": true
        }
    ],
    "clients.destroy": [
        {
            "name": "client",
            "required": true
        }
    ],
    "projects.create": [],
    "projects.store": [],
    "projects.edit": [
        {
            "name": "project",
            "required": true
        }
    ],
    "projects.update": [
        {
            "name": "project",
            "required": true
        }
    ],
    "projects.destroy": [
        {
            "name": "project",
            "required": true
        }
    ],
    "orders.create": [],
    "orders.store": [],
    "orders.edit": [
        {
            "name": "order",
            "required": true
        }
    ],
    "orders.update": [
        {
            "name": "order",
            "required": true
        }
    ],
    "orders.destroy": [
        {
            "name": "order",
            "required": true
        }
    ],
    "invoices.create": [],
    "invoices.store": [],
    "invoices.edit": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "invoices.update": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "invoices.destroy": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "servers.index": [],
    "servers.create": [],
    "servers.store": [],
    "servers.show": [
        {
            "name": "server",
            "required": true
        }
    ],
    "servers.edit": [
        {
            "name": "server",
            "required": true
        }
    ],
    "servers.update": [
        {
            "name": "server",
            "required": true
        }
    ],
    "servers.destroy": [
        {
            "name": "server",
            "required": true
        }
    ],
    "hostings.create": [],
    "hostings.store": [],
    "hostings.edit": [
        {
            "name": "hosting",
            "required": true
        }
    ],
    "hostings.update": [
        {
            "name": "hosting",
            "required": true
        }
    ],
    "hostings.destroy": [
        {
            "name": "hosting",
            "required": true
        }
    ],
    "expense-categories.index": [],
    "expense-categories.create": [],
    "expense-categories.store": [],
    "expense-categories.show": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "expense-categories.edit": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "expense-categories.update": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "expense-categories.destroy": [
        {
            "name": "expense_category",
            "required": true
        }
    ],
    "expenses.index": [],
    "expenses.create": [],
    "expenses.store": [],
    "expenses.show": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "expenses.edit": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "expenses.update": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "expenses.destroy": [
        {
            "name": "expense",
            "required": true
        }
    ],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "roles.index": [],
    "roles.update": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "settings.index": [],
    "settings.update": [],
    "settings.logo": [],
    "settings.test-smtp": [],
    "invoices.send-suspension": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "reports.balance-sheet": [],
    "clients.index": [],
    "clients.show": [
        {
            "name": "client",
            "required": true
        }
    ],
    "projects.index": [],
    "projects.show": [
        {
            "name": "project",
            "required": true
        }
    ],
    "orders.index": [],
    "orders.show": [
        {
            "name": "order",
            "required": true
        }
    ],
    "invoices.index": [],
    "invoices.show": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "hostings.index": [],
    "hostings.show": [
        {
            "name": "hosting",
            "required": true
        }
    ],
    "invoices.pdf": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "invoices.view-pdf": [
        {
            "name": "invoice",
            "required": true
        }
    ],
    "projects.discussions.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.discussions.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.discussions.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "discussion",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.discussions.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "discussion",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.discussions.download": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "attachment",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
